### ISSUE TITLE
Cannot type in pseudocode files

### ISSUE THREAD

**Issue by b08478** [MrCramb/Webucate#2]
when attempting to type into a pseudocode file you cannot

**Comment by ghost** [comment]
Reproduce: 
1. Create a website with Pseudocode or create a site then add it.
2. When selected the Pseudocode provides no option to add text and remains blank.
![Screenshot 2023-01-23 150303](https://user-images.githubusercontent.com/106367368/213968948-305e4940-6bc9-43bc-8b85-441595c3d938.png)

**Comment by MrCramb** [comment]
Fixed
