### ISSUE TITLE
Deleted sites stay in the site tree.

### ISSUE THREAD

**Issue by ghost** [MrCramb/Webucate#3]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by ghost** [comment]
To Reproduce: 
1. Create a site
2. Delete it
3. Open the site tree and it will show

All my sites that I have ever created are showing in the diagram, this also applies for sites that were deleted while in a folder, the ghosts of these sites stay in the parent folder when deleted. Clicking the deleted button while using the site tree will also result in the same problem although a confirmation is given.

**Comment by MrCramb** [comment]
Fixed
