### ISSUE TITLE
SVG does not show in project tree

### ISSUE THREAD

**Issue by Water261** [MrCramb/Webucate#4]
**Describe the bug**
SVG images upload but do not show in the project tree

**To Reproduce**
1. Open a website
2. Attempt to upload an svg image
3. Watch as the upload completes but the image does not show

**Expected behavior**
Image should upload correctly

**Screenshots**

**Desktop (please complete the following information):**
- Firefox 109, Windows 11

**Additional context**

**Comment by ghost** [comment]
Appears to upload and throws no visible errors however the svg doesn't appear in the tree. Trying to access said files by creating an img element with the relevent path and name still shows no image. (Opera GX, Windows 11)

**Comment by MrCramb** [comment]
Support for SVG files has been added :)
