### ISSUE TITLE
Allow site imports from VS code

### ISSUE THREAD

**Issue by ghost** [MrCramb/Webucate#5]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ghost** [comment]
Very hard to do just wanted to ask as it would enable me to work in VS with more tools and transport the finished site back to Webucate for assignments. This could be enable through VS's in built system or by allowing the master folder to be added to the site tree if .html/.js/.css files are present in it. This would also be great if it worked in reverse and we could export a site to VS this would be great and would be much simpler as a feature to download the site folder containing the files would be easier.

**Comment by MrCramb** [comment]
This isn't a feature on the roadmap at the moment. For various reasons, the focus of Webucate is to be the primary coding environment for students.
