### ISSUE TITLE
Open in a new tab button works but the website is still showing on the coding page.

### ISSUE THREAD

**Issue by b08452** [MrCramb/Webucate#7]
open in a tab button works but it doesnt remove the website page from the coding pages.

1. open website
2. click on open in new tab button near the top right
3. wait for website to load on the new page 
4. check back on the coding page and the website will still be in the window

the website isnt meant to stay on the coding page once it has been opened in a new tab until the main page has been refreshed

chrome

**Comment by ghost** [comment]
This problem can be also caused by reloading the page once the website has been launched.

**Comment by MrCramb** [comment]
Fixed
